server:
  servlet:
    context-path: /law-voice
  port: 9010

spring:
  datasource:
    url: jdbc:mysql://122.152.200.208:10743/law_voice?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    url: jdbc:mysql://127.0.0.1:10743/law_voice?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: lv2020

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
  redis:
    host: 127.0.0.1
    port: 6379
#    port: 9206
    password:
    database: 3
    pool:
      max-active: 10
      max-wait: 100
      max-idle: 10
      min-idle: 0
    timeout: 2000

mybatis:
  mapper-locations: classpath:mapping/*.xml
  typeAliasesPackage: com.voice.law.mapper
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.*: